"""image added to tasks

Revision ID: 38900b6e583b
Revises: 8c92e57fc90b
Create Date: 2024-07-04 01:24:32.941894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38900b6e583b'
down_revision = '8c92e57fc90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_image'), ['image'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_image'))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
